### ISSUE TITLE
test fail: getEvaluations - network error on API 32

### ISSUE THREAD

**Issue by duyhungtnn** [bucketeer-io/android-client-sdk#92]
### Problem
- We have 2 test cases fail when run test against Android Emulator API 32.
  + getEvaluations - network error
  + registerEvents - network error
- But its not fail on API 29 (like in the CI/CD). It means on API 32 , the error "network error" is being reported as "timeout error"
<img width="2164" alt="Screenshot 2023-09-21 at 15 46 20" src="https://github.com/bucketeer-io/android-client-sdk/assets/2597710/a647e398-b843-4594-beb1-82f98f1c5c0e">

```
expected instance of: io.bucketeer.sdk.android.BKTException$NetworkException
but was instance of : io.bucketeer.sdk.android.BKTException$TimeoutException
with value          : io.bucketeer.sdk.android.BKTException$TimeoutException: Request timeout error: Connect timed out
expected instance of: io.bucketeer.sdk.android.BKTException$NetworkException
but was instance of : io.bucketeer.sdk.android.BKTException$TimeoutException
with value          : io.bucketeer.sdk.android.BKTException$TimeoutException: Request timeout error: Connect timed out
	at app//io.bucketeer.sdk.android.internal.remote.ApiClientImplTest.registerEvents - network error(ApiClientImplTest.kt:344)
Caused by: io.bucketeer.sdk.android.BKTException$TimeoutException: Request timeout error: Connect timed out
	at app//io.bucketeer.sdk.android.internal.remote.ApiClientExtKt.toBKTException(ApiClientExt.kt:93)
	at app//io.bucketeer.sdk.android.internal.remote.ApiClientImpl.registerEvents(ApiClientImpl.kt:152)
	at app//io.bucketeer.sdk.android.internal.remote.ApiClientImplTest.registerEvents - network error(ApiClientImplTest.kt:339)
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at io.bucketeer.sdk.android.internal.remote.ApiClientImpl.registerEvents(ApiClientImpl.kt:131)
	... 1 more

```

**Comment by duyhungtnn** [comment]
### TODO
- [ ] try to test against API 32 on the CI/CD, so we can find where is the problem
